projects:
  - name: Progetto Taccuino Sanitario Elettronico
    description: |
      Il taccuino personale del fascicolo sanitario elettronico
      Un modello di sviluppo software basato su community Open Source
    documents:
      - project-document-doc
      - another-project-document-doc
    short_name: TP-FSE
    website: none
    tags:
      - sanita'
      - community
      - fascicolo sanitario elettronico
