publisher:
  name: Master Management del Software Libero
  description: |
    Il Master MSL è organizzato dall’Università del Piemonte Orientale,
    Dipartimento di studi per l’Economia, 
    grazie al finanziamento della Regione Piemonte.
  github_organization_url: https://github.com/Master-MSL
  short_name: Master MSL
  website: https://www.managementsoftwarelibero.it/
  tags:
    - documents
    - public
    - software libero
  logo: assets/images/logo.svg
